### ISSUE TITLE
Gameplay task list

### ISSUE THREAD

**Issue by Quozul** [Quozul/Pirikium#1]
### Already added
- [x] Skill tree
- [x] Health and skill orbs
- [x] Sneak
- [x] Languages
- [x] Full-auto weapons
- [x] Check for updates
- [x] Burst mode for auto weapons
- [x] Particles
- [x] Teleporters (removed)
- [x] Pause menu
- [x] Mods

## Gameplay features
- [ ] Pets
- [ ] Vehicles
- [ ] Special attacks
- [ ] Armours
- [ ] Different map themes
- [ ] Weapons that affects target's skills
- [ ] Explosive and flame weapons
- [ ] Random maps
- [ ] Random map events
- [ ] Character customization

## Trading
- [ ] NPCs
- [ ] Villages
- [ ] Trading
- [ ] Quests
- [ ] Potions
- [ ] Recipies (with *brain* skill)
- [ ] Crafting/building

### Looting system
*The looting system will permit the addition of *blocked* objects (weapons, recipies, vehicles, pets, ...)*
- [ ] Looting chests/cards
- [ ] Cards/chests levels (legendary, common, epic, ...)
- [ ] Looting skill (increases the chances of having rare loots)

## Other features
- [ ] Auto updater
- [ ] Game modes
- [ ] Scaling
- [ ] Mod editor/creator
- [ ] Mods workshop
- [ ] Multiplayer
